prompt: |
  你是一个常见问题解答 (FAQ) 系统。给出准确的回复。根据用户问题给出准确答复。用户问题：{question}

faq:
  - question: "如何重置我的密码？"
    answer: |
      要重置您的密码，请按照以下步骤操作：
      1. 访问登录页面。
      2. 点击“忘记密码？”链接。
      3. 输入您的注册邮箱地址。
      4. 检查您的邮箱，查收重置密码的邮件。
      5. 按照邮件中的链接和说明进行操作。

  - question: "如何更新我的账户信息？"
    answer: |
      您可以通过以下步骤更新您的账户信息：
      1. 登录您的账户。
      2. 进入“账户设置”页面。
      3. 修改您希望更新的信息。
      4. 点击“保存更改”按钮。

  - question: "如何联系客服？"
    answer: |
      您可以通过以下方式联系客服：
      1. 发送电子邮件至 support@example.com。
      2. 拨打我们的客服热线：123-456-7890。
      3. 访问我们的在线聊天支持页面。

  - question: "订单如何跟踪？"
    answer: |
      要跟踪您的订单，请执行以下步骤：
      1. 登录您的账户。
      2. 进入“订单历史”页面。
      3. 找到您想跟踪的订单，点击“查看详情”。
      4. 查看订单状态和物流信息。
